### ISSUE TITLE
好像不能使用啊

### ISSUE THREAD

**Issue by youwillbe** [whyour/issue-blog#182]
报错信息如下：
```
[2021-11-12 10:50:13.584] [exthost] [error] TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
	at macosRelease (/Users/kangyu/.vscode/extensions/whyour.issue-blog-1.0.2/node_modules/macos-release/index.js:26:26)
	at osName (/Users/kangyu/.vscode/extensions/whyour.issue-blog-1.0.2/node_modules/os-name/index.js:21:18)
	at getUserAgent (/Users/kangyu/.vscode/extensions/whyour.issue-blog-1.0.2/node_modules/universal-user-agent/dist-node/index.js:11:53)
	at parseOptions (/Users/kangyu/.vscode/extensions/whyour.issue-blog-1.0.2/node_modules/@octokit/rest/lib/parse-client-options.js:80:57)
	at new Octokit (/Users/kangyu/.vscode/extensions/whyour.issue-blog-1.0.2/node_modules/@octokit/rest/lib/constructor.js:23:31)
	at new Github (/Users/kangyu/.vscode/extensions/whyour.issue-blog-1.0.2/out/github.js:43:24)
	at new Upload (/Users/kangyu/.vscode/extensions/whyour.issue-blog-1.0.2/out/upload.js:17:23)
	at /Users/kangyu/.vscode/extensions/whyour.issue-blog-1.0.2/out/commands.js:56:24
	at Generator.next (<anonymous>)
	at fulfilled (/Users/kangyu/.vscode/extensions/whyour.issue-blog-1.0.2/out/commands.js:5:58)
	at processTicksAndRejections (internal/process/task_queues.js:93:5) extension.getIssues {"value":"whyour.issue-blog","_lower":"whyour.issue-blog"}
```

**Comment by YouWillBe** [comment]
奇怪哎，我把你的代码拉下去调试的时候是可以跑的，怎么出来就不能跑了

**Comment by YouWillBe** [comment]
自己打包成vsix安装之后也是可以的，可能是你发布的包有问题了

**Comment by whyour** [comment]
更新 1.0.3 试试
